server:
  port: 8065
  servlet:
    context-path: /microcloud

spring:
  datasource:
    name: dev
    #数据库连接池类型DBCP c3p0 druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      primary:
        url: jdbc:mysql://192.168.0.68:3306/micro_bim_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        jdbc-url: jdbc:mysql://192.168.0.68:3306/micro_bim_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: BIM@123%$#qwe
        driver-class-name: com.mysql.cj.jdbc.Driver
      secondary:
        url: jdbc:mysql://rm-8vbg17fz5r38qq22jwo.mysql.zhangbei.rds.aliyuncs.com:3306/ding_cloud_push?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        jdbc-url: jdbc:mysql://rm-8vbg17fz5r38qq22jwo.mysql.zhangbei.rds.aliyuncs.com:3306/ding_cloud_push?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: bim
        password: Bim123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 7
    host: 192.168.0.68
    port: 6375
    password: 123
    lettuce:
      pool:
        max-active: 800
        max-wait:
          -1ms
        max-idle: 10
        min-idle: 2
    timeout:
      10000ms

micro:
  model:
    path:
      netprefix: http://micro.bdip.com/bim
      diskprefix: /data